# Generated by Django 4.1.5 on 2023-01-12 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Size_Shoes',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Size_shirt',
        ),
        migrations.AddField(
            model_name='cart',
            name='Size',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Deliverd', 'Deliverd'), ('On the Way', 'On the way'), ('ACCEPTED', 'ACCEPTED'), ('cancel', 'cancel')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TW', 'Topwear'), ('SH', 'SHOES'), ('BW', 'Bottomwear')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Size_shirt',
        ),
        migrations.DeleteModel(
            name='Size_Shoes',
        ),
    ]
