# Generated by Django 4.1.5 on 2023-01-15 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_orderplaced_status_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='Size',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('ACCEPTED', 'ACCEPTED'), ('cancel', 'cancel'), ('Deliverd', 'Deliverd'), ('On the Way', 'On the way')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BW', 'Bottomwear'), ('TW', 'Topwear'), ('W', '\tWATCH'), ('SH', 'SHOES')], max_length=50),
        ),
    ]
